name: vizor
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ^3.6.0
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  # 
  flutter_bloc: ^9.1.1
  shared_preferences: ^2.5.3
  flutter_svg: ^2.2.0
  intl: ^0.19.0
  go_router: ^16.1.0
  dio: ^5.8.0+1
  connectivity_plus: ^6.1.4
  cached_network_image: ^3.4.1
  smooth_page_indicator: ^1.2.1
  image_picker: ^1.1.2
  flutter_dotenv: ^5.2.1
  pinput: ^5.0.1
  # share_plus: ^10.1.4
  # 
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/
    - assets/fonts/
  # fonts:
  #   - family: w400
  #     fonts:
  #       - asset: assets/fonts/Inter-Regular.ttf
  #   - family: w500
  #     fonts:
  #       - asset: assets/fonts/Inter-Medium.ttf
  #   - family: w600
  #     fonts:
  #       - asset: assets/fonts/Inter-SemiBold.ttf
  #   - family: w700
  #     fonts:
  #       - asset: assets/fonts/Inter-Bold.ttf
